export interface WordTranslation {
  word: string;
  hindi: string;
  pronunciation?: string;
}

export interface ContentItem {
  id: number;
  title: string;
  content: string;
  wordTranslations: WordTranslation[];
}

export const ESSAYS_CONTENT: ContentItem[] = [
  {
    id: 1,
    title: "My Daily Routine",
    content: "Every morning I wake up at six o'clock. I brush my teeth and take a shower. Then I have breakfast with my family. After breakfast, I go to work by bus. In the evening, I return home and have dinner.",
    wordTranslations: [
      { word: "morning", hindi: "सुबह", pronunciation: "ˈmɔːrnɪŋ" },
      { word: "wake", hindi: "जागना", pronunciation: "weɪk" },
      { word: "o'clock", hindi: "बजे", pronunciation: "əˈklɑːk" },
      { word: "brush", hindi: "ब्रश करना", pronunciation: "brʌʃ" },
      { word: "teeth", hindi: "दांत", pronunciation: "tiːθ" },
      { word: "shower", hindi: "नहाना", pronunciation: "ˈʃaʊər" },
      { word: "breakfast", hindi: "नाश्ता", pronunciation: "ˈbrekfəst" },
      { word: "family", hindi: "परिवार", pronunciation: "ˈfæməli" },
      { word: "work", hindi: "काम", pronunciation: "wɜːrk" },
      { word: "bus", hindi: "बस", pronunciation: "bʌs" },
      { word: "evening", hindi: "शाम", pronunciation: "ˈiːvnɪŋ" },
      { word: "return", hindi: "वापस आना", pronunciation: "rɪˈtɜːrn" },
      { word: "home", hindi: "घर", pronunciation: "hoʊm" },
      { word: "dinner", hindi: "रात का खाना", pronunciation: "ˈdɪnər" }
    ]
  },
  {
    id: 2,
    title: "Diwali Celebration",
    content: "Diwali is the festival of lights celebrated across India. Families decorate their homes with colorful rangoli and diyas. We burst crackers and share sweets with neighbors. This festival brings joy and prosperity to everyone.",
    wordTranslations: [
      { word: "festival", hindi: "त्योहार", pronunciation: "ˈfestɪvl" },
      { word: "lights", hindi: "रोशनी", pronunciation: "laɪts" },
      { word: "celebrated", hindi: "मनाया जाता है", pronunciation: "ˈseləbreɪtɪd" },
      { word: "decorate", hindi: "सजाना", pronunciation: "ˈdekəreɪt" },
      { word: "colorful", hindi: "रंगबिरंगा", pronunciation: "ˈkʌlərfl" },
      { word: "rangoli", hindi: "रंगोली", pronunciation: "ˈrʌŋɡoʊli" },
      { word: "diyas", hindi: "दिये", pronunciation: "ˈdiːjɑːz" },
      { word: "burst", hindi: "फोड़ना", pronunciation: "bɜːrst" },
      { word: "crackers", hindi: "पटाखे", pronunciation: "ˈkrækərz" },
      { word: "sweets", hindi: "मिठाई", pronunciation: "swiːts" },
      { word: "neighbors", hindi: "पड़ोसी", pronunciation: "ˈneɪbərz" },
      { word: "joy", hindi: "खुशी", pronunciation: "dʒɔɪ" },
      { word: "prosperity", hindi: "समृद्धि", pronunciation: "prɑːˈsperəti" }
    ]
  },
  {
    id: 3,
    title: "Indian Street Food",
    content: "Indian street food is famous worldwide for its amazing taste. From Mumbai's vada pav to Delhi's chaat, every city has unique flavors. Street vendors prepare fresh food with secret spices that make it delicious.",
    wordTranslations: [
      { word: "street", hindi: "सड़क", pronunciation: "striːt" },
      { word: "food", hindi: "खाना", pronunciation: "fuːd" },
      { word: "famous", hindi: "प्रसिद्ध", pronunciation: "ˈfeɪməs" },
      { word: "worldwide", hindi: "दुनिया भर में", pronunciation: "ˈwɜːrldwaɪd" },
      { word: "amazing", hindi: "अद्भुत", pronunciation: "əˈmeɪzɪŋ" },
      { word: "taste", hindi: "स्वाद", pronunciation: "teɪst" },
      { word: "unique", hindi: "अनोखा", pronunciation: "juˈniːk" },
      { word: "flavors", hindi: "स्वाद", pronunciation: "ˈfleɪvərz" },
      { word: "vendors", hindi: "विक्रेता", pronunciation: "ˈvendərz" },
      { word: "prepare", hindi: "तैयार करना", pronunciation: "prɪˈper" },
      { word: "fresh", hindi: "ताज़ा", pronunciation: "freʃ" },
      { word: "secret", hindi: "गुप्त", pronunciation: "ˈsiːkrət" },
      { word: "spices", hindi: "मसाले", pronunciation: "ˈspaɪsɪz" },
      { word: "delicious", hindi: "स्वादिष्ट", pronunciation: "dɪˈlɪʃəs" }
    ]
  },
  {
    id: 4,
    title: "Monsoon Season",
    content: "The monsoon brings relief from hot summer weather. Dark clouds cover the sky and heavy rain falls for hours. Farmers rejoice as their crops get much-needed water. Children play in puddles and enjoy paper boats.",
    wordTranslations: [
      { word: "monsoon", hindi: "मानसून", pronunciation: "mɑːnˈsuːn" },
      { word: "brings", hindi: "लाता है", pronunciation: "brɪŋz" },
      { word: "relief", hindi: "राहत", pronunciation: "rɪˈliːf" },
      { word: "summer", hindi: "गर्मी", pronunciation: "ˈsʌmər" },
      { word: "weather", hindi: "मौसम", pronunciation: "ˈweðər" },
      { word: "clouds", hindi: "बादल", pronunciation: "klaʊdz" },
      { word: "cover", hindi: "ढकना", pronunciation: "ˈkʌvər" },
      { word: "heavy", hindi: "भारी", pronunciation: "ˈhevi" },
      { word: "rain", hindi: "बारिश", pronunciation: "reɪn" },
      { word: "hours", hindi: "घंटे", pronunciation: "aʊərz" },
      { word: "farmers", hindi: "किसान", pronunciation: "ˈfɑːrmərz" },
      { word: "rejoice", hindi: "खुश होना", pronunciation: "rɪˈdʒɔɪs" },
      { word: "crops", hindi: "फसल", pronunciation: "krɑːps" },
      { word: "needed", hindi: "जरूरी", pronunciation: "ˈniːdəd" },
      { word: "puddles", hindi: "पानी के गड्ढे", pronunciation: "ˈpʌdlz" },
      { word: "boats", hindi: "नाव", pronunciation: "boʊts" }
    ]
  },
  {
    id: 5,
    title: "Cricket Fever in India",
    content: "Cricket is more than a sport in India. When the Indian team plays, millions gather around television screens. Streets become empty as everyone watches the match. Victory celebrations continue throughout the night with drums and dancing.",
    wordTranslations: [
      { word: "cricket", hindi: "क्रिकेट", pronunciation: "ˈkrɪkɪt" },
      { word: "fever", hindi: "बुखार", pronunciation: "ˈfiːvər" },
      { word: "sport", hindi: "खेल", pronunciation: "spɔːrt" },
      { word: "team", hindi: "टीम", pronunciation: "tiːm" },
      { word: "plays", hindi: "खेलती है", pronunciation: "pleɪz" },
      { word: "millions", hindi: "लाखों", pronunciation: "ˈmɪljənz" },
      { word: "gather", hindi: "इकट्ठा होना", pronunciation: "ˈɡæðər" },
      { word: "television", hindi: "टेलीविजन", pronunciation: "ˈteləvɪʒn" },
      { word: "screens", hindi: "स्क्रीन", pronunciation: "skriːnz" },
      { word: "streets", hindi: "सड़कें", pronunciation: "striːts" },
      { word: "empty", hindi: "खाली", pronunciation: "ˈempti" },
      { word: "match", hindi: "मैच", pronunciation: "mætʃ" },
      { word: "victory", hindi: "जीत", pronunciation: "ˈvɪktəri" },
      { word: "celebrations", hindi: "उत्सव", pronunciation: "ˌseləˈbreɪʃnz" },
      { word: "continue", hindi: "जारी रहना", pronunciation: "kənˈtɪnju" },
      { word: "drums", hindi: "ढोल", pronunciation: "drʌmz" },
      { word: "dancing", hindi: "नृत्य", pronunciation: "ˈdænsɪŋ" }
    ]
  },
  {
    id: 6,
    title: "Indian Spices and Their Benefits",
    content: "Indian cuisine uses various spices that are healthy and flavorful. Turmeric fights infections and reduces inflammation. Cumin aids digestion while cardamom freshens breath. These natural ingredients make Indian food both tasty and nutritious.",
    wordTranslations: [
      { word: "cuisine", hindi: "व्यंजन", pronunciation: "kwɪˈziːn" },
      { word: "spices", hindi: "मसाले", pronunciation: "ˈspaɪsɪz" },
      { word: "healthy", hindi: "स्वस्थ", pronunciation: "ˈhelθi" },
      { word: "flavorful", hindi: "स्वादिष्ट", pronunciation: "ˈfleɪvərfl" },
      { word: "turmeric", hindi: "हल्दी", pronunciation: "ˈtɜːrmərɪk" },
      { word: "fights", hindi: "लड़ता है", pronunciation: "faɪts" },
      { word: "infections", hindi: "संक्रमण", pronunciation: "ɪnˈfekʃnz" },
      { word: "reduces", hindi: "कम करता है", pronunciation: "rɪˈduːsɪz" },
      { word: "inflammation", hindi: "सूजन", pronunciation: "ˌɪnfləˈmeɪʃn" },
      { word: "cumin", hindi: "जीरा", pronunciation: "ˈkuːmɪn" },
      { word: "aids", hindi: "सहायता करता है", pronunciation: "eɪdz" },
      { word: "digestion", hindi: "पाचन", pronunciation: "daɪˈdʒestʃən" },
      { word: "cardamom", hindi: "इलायची", pronunciation: "ˈkɑːrdəməm" },
      { word: "freshens", hindi: "ताज़ा करता है", pronunciation: "ˈfreʃənz" },
      { word: "breath", hindi: "सांस", pronunciation: "breθ" },
      { word: "natural", hindi: "प्राकृतिक", pronunciation: "ˈnætʃərəl" },
      { word: "ingredients", hindi: "सामग्री", pronunciation: "ɪnˈɡriːdiənts" },
      { word: "nutritious", hindi: "पौष्टिक", pronunciation: "nuˈtrɪʃəs" }
    ]
  },
  {
    id: 7,
    title: "The Beauty of Himalayas",
    content: "The Himalayan mountains are India's crown jewel. Snow-capped peaks touch the sky while rivers flow down the valleys. Many pilgrims visit sacred temples hidden in these mountains. The fresh air and peaceful environment provide perfect escape from city life.",
    wordTranslations: [
      { word: "mountains", hindi: "पहाड़", pronunciation: "ˈmaʊntənz" },
      { word: "crown", hindi: "मुकुट", pronunciation: "kraʊn" },
      { word: "jewel", hindi: "रत्न", pronunciation: "ˈdʒuːəl" },
      { word: "snow-capped", hindi: "बर्फ से ढके", pronunciation: "snoʊ kæpt" },
      { word: "peaks", hindi: "चोटियां", pronunciation: "piːks" },
      { word: "touch", hindi: "छूना", pronunciation: "tʌtʃ" },
      { word: "sky", hindi: "आसमान", pronunciation: "skaɪ" },
      { word: "rivers", hindi: "नदियां", pronunciation: "ˈrɪvərz" },
      { word: "flow", hindi: "बहना", pronunciation: "floʊ" },
      { word: "valleys", hindi: "घाटी", pronunciation: "ˈvæliz" },
      { word: "pilgrims", hindi: "तीर्थयात्री", pronunciation: "ˈpɪlɡrəmz" },
      { word: "sacred", hindi: "पवित्र", pronunciation: "ˈseɪkrəd" },
      { word: "temples", hindi: "मंदिर", pronunciation: "ˈtemplz" },
      { word: "hidden", hindi: "छिपे हुए", pronunciation: "ˈhɪdn" },
      { word: "fresh", hindi: "ताज़ी", pronunciation: "freʃ" },
      { word: "peaceful", hindi: "शांतिपूर्ण", pronunciation: "ˈpiːsfl" },
      { word: "environment", hindi: "वातावरण", pronunciation: "ɪnˈvaɪrənmənt" },
      { word: "escape", hindi: "भागना", pronunciation: "ɪˈskeɪp" }
    ]
  },
  {
    id: 8,
    title: "Indian Railways Journey",
    content: "Traveling by train in India is an unforgettable experience. From luxury coaches to general compartments, trains carry millions daily. Vendors sell tea, snacks, and meals at every station. The journey offers beautiful landscapes and chance to meet diverse people.",
    wordTranslations: [
      { word: "traveling", hindi: "यात्रा करना", pronunciation: "ˈtrævəlɪŋ" },
      { word: "train", hindi: "ट्रेन", pronunciation: "treɪn" },
      { word: "unforgettable", hindi: "अविस्मरणीय", pronunciation: "ˌʌnfərˈɡetəbl" },
      { word: "experience", hindi: "अनुभव", pronunciation: "ɪkˈspɪriəns" },
      { word: "luxury", hindi: "लक्जरी", pronunciation: "ˈlʌkʃəri" },
      { word: "coaches", hindi: "डिब्बे", pronunciation: "ˈkoʊtʃɪz" },
      { word: "general", hindi: "सामान्य", pronunciation: "ˈdʒenərəl" },
      { word: "compartments", hindi: "डिब्बे", pronunciation: "kəmˈpɑːrtmənts" },
      { word: "carry", hindi: "ले जाना", pronunciation: "ˈkæri" },
      { word: "millions", hindi: "लाखों", pronunciation: "ˈmɪljənz" },
      { word: "daily", hindi: "रोज़ाना", pronunciation: "ˈdeɪli" },
      { word: "vendors", hindi: "विक्रेता", pronunciation: "ˈvendərz" },
      { word: "snacks", hindi: "नाश्ता", pronunciation: "snæks" },
      { word: "meals", hindi: "भोजन", pronunciation: "miːlz" },
      { word: "station", hindi: "स्टेशन", pronunciation: "ˈsteɪʃn" },
      { word: "journey", hindi: "यात्रा", pronunciation: "ˈdʒɜːrni" },
      { word: "offers", hindi: "प्रदान करता है", pronunciation: "ˈɔːfərz" },
      { word: "landscapes", hindi: "दृश्य", pronunciation: "ˈlændskeɪps" },
      { word: "chance", hindi: "अवसर", pronunciation: "tʃæns" },
      { word: "diverse", hindi: "विविध", pronunciation: "daɪˈvɜːrs" }
    ]
  },
  {
    id: 9,
    title: "Village Life in India",
    content: "Indian villages preserve traditional culture and simple living. Farmers wake up early to tend their fields with buffaloes and tractors. Children attend schools while grandparents share ancient stories. Community festivals unite everyone in celebration and joy.",
    wordTranslations: [
      { word: "villages", hindi: "गांव", pronunciation: "ˈvɪlɪdʒɪz" },
      { word: "preserve", hindi: "संरक्षित करना", pronunciation: "prɪˈzɜːrv" },
      { word: "traditional", hindi: "पारंपरिक", pronunciation: "trəˈdɪʃənəl" },
      { word: "culture", hindi: "संस्कृति", pronunciation: "ˈkʌltʃər" },
      { word: "simple", hindi: "सरल", pronunciation: "ˈsɪmpl" },
      { word: "living", hindi: "जीवन", pronunciation: "ˈlɪvɪŋ" },
      { word: "farmers", hindi: "किसान", pronunciation: "ˈfɑːrmərz" },
      { word: "early", hindi: "जल्दी", pronunciation: "ˈɜːrli" },
      { word: "tend", hindi: "देखभाल करना", pronunciation: "tend" },
      { word: "fields", hindi: "खेत", pronunciation: "fiːldz" },
      { word: "buffaloes", hindi: "भैंस", pronunciation: "ˈbʌfəloʊz" },
      { word: "tractors", hindi: "ट्रैक्टर", pronunciation: "ˈtræktərz" },
      { word: "children", hindi: "बच्चे", pronunciation: "ˈtʃɪldrən" },
      { word: "attend", hindi: "जाना", pronunciation: "əˈtend" },
      { word: "schools", hindi: "स्कूल", pronunciation: "skuːlz" },
      { word: "grandparents", hindi: "दादा-दादी", pronunciation: "ˈɡrænˌperənts" },
      { word: "share", hindi: "साझा करना", pronunciation: "ʃer" },
      { word: "ancient", hindi: "प्राचीन", pronunciation: "ˈeɪnʃənt" },
      { word: "stories", hindi: "कहानियां", pronunciation: "ˈstɔːriz" },
      { word: "community", hindi: "समुदाय", pronunciation: "kəˈmjuːnəti" },
      { word: "festivals", hindi: "त्योहार", pronunciation: "ˈfestɪvəlz" },
      { word: "unite", hindi: "एकजुट करना", pronunciation: "juˈnaɪt" },
      { word: "celebration", hindi: "उत्सव", pronunciation: "ˌseləˈbreɪʃn" }
    ]
  },
  {
    id: 10,
    title: "The Sacred Ganges River",
    content: "The Ganges is considered the holiest river in India. Millions of devotees take holy baths believing it cleanses their sins. The river flows through many important cities providing water for agriculture. Despite pollution challenges, efforts continue to clean this sacred waterway.",
    wordTranslations: [
      { word: "sacred", hindi: "पवित्र", pronunciation: "ˈseɪkrəd" },
      { word: "considered", hindi: "माना जाता है", pronunciation: "kənˈsɪdərd" },
      { word: "holiest", hindi: "सबसे पवित्र", pronunciation: "ˈhoʊliəst" },
      { word: "river", hindi: "नदी", pronunciation: "ˈrɪvər" },
      { word: "millions", hindi: "लाखों", pronunciation: "ˈmɪljənz" },
      { word: "devotees", hindi: "भक्त", pronunciation: "ˌdevəˈtiːz" },
      { word: "holy", hindi: "पवित्र", pronunciation: "ˈhoʊli" },
      { word: "baths", hindi: "स्नान", pronunciation: "bæθs" },
      { word: "believing", hindi: "विश्वास करना", pronunciation: "bɪˈliːvɪŋ" },
      { word: "cleanses", hindi: "साफ करता है", pronunciation: "ˈklenzɪz" },
      { word: "sins", hindi: "पाप", pronunciation: "sɪnz" },
      { word: "flows", hindi: "बहती है", pronunciation: "floʊz" },
      { word: "through", hindi: "से होकर", pronunciation: "θruː" },
      { word: "important", hindi: "महत्वपूर्ण", pronunciation: "ɪmˈpɔːrtənt" },
      { word: "cities", hindi: "शहर", pronunciation: "ˈsɪtiz" },
      { word: "providing", hindi: "प्रदान करना", pronunciation: "prəˈvaɪdɪŋ" },
      { word: "water", hindi: "पानी", pronunciation: "ˈwɔːtər" },
      { word: "agriculture", hindi: "कृषि", pronunciation: "ˈæɡrɪkʌltʃər" },
      { word: "despite", hindi: "के बावजूद", pronunciation: "dɪˈspaɪt" },
      { word: "pollution", hindi: "प्रदूषण", pronunciation: "pəˈluːʃn" },
      { word: "challenges", hindi: "चुनौतियां", pronunciation: "ˈtʃælɪndʒəz" },
      { word: "efforts", hindi: "प्रयास", pronunciation: "ˈefərts" },
      { word: "continue", hindi: "जारी रखना", pronunciation: "kənˈtɪnju" },
      { word: "clean", hindi: "साफ करना", pronunciation: "kliːn" },
      { word: "waterway", hindi: "जलमार्ग", pronunciation: "ˈwɔːtərweɪ" }
    ]
  },
  {
    id: 11,
    title: "Bollywood and Indian Cinema",
    content: "Bollywood produces the largest number of films globally. Indian cinema reflects our diverse culture and traditions. Famous actors like Shah Rukh Khan and Deepika Padukone are known worldwide. These movies spread Indian values and entertainment across the globe.",
    wordTranslations: [
      { word: "produces", hindi: "बनाता है", pronunciation: "prəˈduːsəz" },
      { word: "largest", hindi: "सबसे बड़ा", pronunciation: "ˈlɑːrdʒəst" },
      { word: "films", hindi: "फिल्में", pronunciation: "fɪlmz" },
      { word: "cinema", hindi: "सिनेमा", pronunciation: "ˈsɪnəmə" },
      { word: "reflects", hindi: "दर्शाता है", pronunciation: "rɪˈflekts" },
      { word: "diverse", hindi: "विविध", pronunciation: "daɪˈvɜːrs" },
      { word: "culture", hindi: "संस्कृति", pronunciation: "ˈkʌltʃər" },
      { word: "traditions", hindi: "परंपराएं", pronunciation: "trəˈdɪʃnz" },
      { word: "famous", hindi: "प्रसिद्ध", pronunciation: "ˈfeɪməs" },
      { word: "actors", hindi: "अभिनेता", pronunciation: "ˈæktərz" },
      { word: "worldwide", hindi: "दुनिया भर में", pronunciation: "ˈwɜːrldwaɪd" },
      { word: "movies", hindi: "फिल्में", pronunciation: "ˈmuːviz" },
      { word: "spread", hindi: "फैलाती हैं", pronunciation: "spred" },
      { word: "values", hindi: "मूल्य", pronunciation: "ˈvæljuːz" },
      { word: "entertainment", hindi: "मनोरंजन", pronunciation: "ˌentərˈteɪnmənt" }
    ]
  },
  {
    id: 12,
    title: "Yoga and Meditation",
    content: "Yoga originated in ancient India thousands of years ago. This practice combines physical exercises with mental peace. Millions of people worldwide now practice yoga daily. It helps reduce stress and improves overall health and well-being.",
    wordTranslations: [
      { word: "yoga", hindi: "योग", pronunciation: "ˈjoʊɡə" },
      { word: "originated", hindi: "उत्पन्न हुआ", pronunciation: "əˈrɪdʒəneɪtəd" },
      { word: "ancient", hindi: "प्राचीन", pronunciation: "ˈeɪnʃənt" },
      { word: "thousands", hindi: "हजारों", pronunciation: "ˈθaʊzəndz" },
      { word: "practice", hindi: "अभ्यास", pronunciation: "ˈpræktəs" },
      { word: "combines", hindi: "मिलाता है", pronunciation: "kəmˈbaɪnz" },
      { word: "physical", hindi: "शारीरिक", pronunciation: "ˈfɪzɪkəl" },
      { word: "exercises", hindi: "व्यायाम", pronunciation: "ˈeksərˌsaɪzəz" },
      { word: "mental", hindi: "मानसिक", pronunciation: "ˈmentl" },
      { word: "peace", hindi: "शांति", pronunciation: "piːs" },
      { word: "worldwide", hindi: "दुनिया भर में", pronunciation: "ˈwɜːrldwaɪd" },
      { word: "daily", hindi: "रोज़ाना", pronunciation: "ˈdeɪli" },
      { word: "reduce", hindi: "कम करना", pronunciation: "rɪˈduːs" },
      { word: "stress", hindi: "तनाव", pronunciation: "stres" },
      { word: "improves", hindi: "सुधारता है", pronunciation: "ɪmˈpruːvz" },
      { word: "health", hindi: "स्वास्थ्य", pronunciation: "helθ" }
    ]
  },
  {
    id: 13,
    title: "The Taj Mahal",
    content: "The Taj Mahal in Agra is one of the Seven Wonders of the World. Shah Jahan built this beautiful monument for his beloved wife Mumtaz. The white marble structure changes colors throughout the day. Millions of tourists visit this symbol of eternal love every year.",
    wordTranslations: [
      { word: "seven", hindi: "सात", pronunciation: "ˈsevən" },
      { word: "wonders", hindi: "अजूबे", pronunciation: "ˈwʌndərz" },
      { word: "built", hindi: "बनवाया", pronunciation: "bɪlt" },
      { word: "monument", hindi: "स्मारक", pronunciation: "ˈmɑːnjumənt" },
      { word: "beloved", hindi: "प्रिय", pronunciation: "bɪˈlʌvd" },
      { word: "wife", hindi: "पत्नी", pronunciation: "waɪf" },
      { word: "white", hindi: "सफेद", pronunciation: "waɪt" },
      { word: "marble", hindi: "संगमरमर", pronunciation: "ˈmɑːrbəl" },
      { word: "structure", hindi: "संरचना", pronunciation: "ˈstrʌktʃər" },
      { word: "changes", hindi: "बदलती है", pronunciation: "ˈtʃeɪndʒəz" },
      { word: "colors", hindi: "रंग", pronunciation: "ˈkʌlərz" },
      { word: "throughout", hindi: "पूरे", pronunciation: "θruˈaʊt" },
      { word: "tourists", hindi: "पर्यटक", pronunciation: "ˈtʊrəsts" },
      { word: "symbol", hindi: "प्रतीक", pronunciation: "ˈsɪmbəl" },
      { word: "eternal", hindi: "अनंत", pronunciation: "ɪˈtɜːrnəl" },
      { word: "love", hindi: "प्रेम", pronunciation: "lʌv" }
    ]
  },
  {
    id: 14,
    title: "Indian Festivals",
    content: "India celebrates numerous colorful festivals throughout the year. Holi brings colors and joy in spring season. Dussehra celebrates the victory of good over evil. Each festival has unique traditions that bring families and communities together in celebration.",
    wordTranslations: [
      { word: "celebrates", hindi: "मनाता है", pronunciation: "ˈseləbreɪts" },
      { word: "numerous", hindi: "अनेक", pronunciation: "ˈnuːmərəs" },
      { word: "colorful", hindi: "रंगबिरंगे", pronunciation: "ˈkʌlərfl" },
      { word: "festivals", hindi: "त्योहार", pronunciation: "ˈfestəvəlz" },
      { word: "throughout", hindi: "पूरे", pronunciation: "θruˈaʊt" },
      { word: "brings", hindi: "लाता है", pronunciation: "brɪŋz" },
      { word: "spring", hindi: "वसंत", pronunciation: "sprɪŋ" },
      { word: "season", hindi: "मौसम", pronunciation: "ˈsiːzən" },
      { word: "victory", hindi: "जीत", pronunciation: "ˈvɪktəri" },
      { word: "good", hindi: "अच्छाई", pronunciation: "ɡʊd" },
      { word: "evil", hindi: "बुराई", pronunciation: "ˈiːvəl" },
      { word: "unique", hindi: "अनोखी", pronunciation: "juˈniːk" },
      { word: "traditions", hindi: "परंपराएं", pronunciation: "trəˈdɪʃnz" },
      { word: "families", hindi: "परिवार", pronunciation: "ˈfæməliz" },
      { word: "communities", hindi: "समुदाय", pronunciation: "kəˈmjuːnətिज़" },
      { word: "together", hindi: "साथ", pronunciation: "təˈɡeðər" }
    ]
  },
  {
    id: 15,
    title: "Indian Markets and Bazaars",
    content: "Indian markets are vibrant places full of colors, sounds, and aromas. From silk sarees to golden jewelry, vendors sell everything imaginable. Customers bargain with shopkeepers in a friendly manner. These bustling bazaars are the heart of Indian commercial life.",
    wordTranslations: [
      { word: "markets", hindi: "बाज़ार", pronunciation: "ˈmɑːrkəts" },
      { word: "vibrant", hindi: "जीवंत", pronunciation: "ˈvaɪbrənt" },
      { word: "full", hindi: "भरे हुए", pronunciation: "fʊl" },
      { word: "sounds", hindi: "आवाज़ें", pronunciation: "saʊndz" },
      { word: "aromas", hindi: "खुशबू", pronunciation: "əˈroʊməz" },
      { word: "silk", hindi: "रेशम", pronunciation: "sɪlk" },
      { word: "sarees", hindi: "साड़ी", pronunciation: "ˈsɑːriːz" },
      { word: "golden", hindi: "सुनहरे", pronunciation: "ˈɡoʊldən" },
      { word: "jewelry", hindi: "आभूषण", pronunciation: "ˈdʒuːəlri" },
      { word: "vendors", hindi: "विक्रेता", pronunciation: "ˈvendərz" },
      { word: "everything", hindi: "सब कुछ", pronunciation: "ˈevriθɪŋ" },
      { word: "imaginable", hindi: "कल्पनीय", pronunciation: "ɪˈmædʒənəbl" },
      { word: "customers", hindi: "ग्राहक", pronunciation: "ˈkʌstəmərz" },
      { word: "bargain", hindi: "मोल-भाव करना", pronunciation: "ˈbɑːrɡən" },
      { word: "shopkeepers", hindi: "दुकानदार", pronunciation: "ˈʃɑːpˌkiːpərz" },
      { word: "friendly", hindi: "मित्रवत", pronunciation: "ˈfrendli" },
      { word: "bustling", hindi: "हलचल भरे", pronunciation: "ˈbʌsəlɪŋ" },
      { word: "heart", hindi: "दिल", pronunciation: "hɑːrt" },
      { word: "commercial", hindi: "व्यापारिक", pronunciation: "kəˈmɜːrʃəl" }
    ]
  }
];

export const STORIES_CONTENT: ContentItem[] = [
  {
    id: 1,
    title: "The Wise Elephant",
    content: "In a jungle near Mysore, lived a wise old elephant named Ganesha. When drought came, he remembered an ancient water source. He led all animals through dangerous paths to safety. His wisdom saved the entire forest community during the crisis.",
    wordTranslations: [
      { word: "jungle", hindi: "जंगल", pronunciation: "ˈdʒʌŋɡəl" },
      { word: "wise", hindi: "बुद्धिमान", pronunciation: "waɪz" },
      { word: "elephant", hindi: "हाथी", pronunciation: "ˈeləfənt" },
      { word: "named", hindi: "नाम", pronunciation: "neɪmd" },
      { word: "drought", hindi: "सूखा", pronunciation: "draʊt" },
      { word: "came", hindi: "आया", pronunciation: "keɪm" },
      { word: "remembered", hindi: "याद किया", pronunciation: "rɪˈmembərd" },
      { word: "ancient", hindi: "प्राचीन", pronunciation: "ˈeɪnʃənt" },
      { word: "source", hindi: "स्रोत", pronunciation: "sɔːrs" },
      { word: "led", hindi: "नेतृत्व किया", pronunciation: "led" },
      { word: "animals", hindi: "जानवर", pronunciation: "ˈænəməlz" },
      { word: "through", hindi: "से होकर", pronunciation: "θruː" },
      { word: "dangerous", hindi: "खतरनाक", pronunciation: "ˈdeɪndʒərəs" },
      { word: "paths", hindi: "रास्ते", pronunciation: "pæθs" },
      { word: "safety", hindi: "सुरक्षा", pronunciation: "ˈseɪfti" },
      { word: "wisdom", hindi: "बुद्धि", pronunciation: "ˈwɪzdəm" },
      { word: "saved", hindi: "बचाया", pronunciation: "seɪvd" },
      { word: "entire", hindi: "पूरा", pronunciation: "ɪnˈtaɪər" },
      { word: "forest", hindi: "जंगल", pronunciation: "ˈfɔːrəst" },
      { word: "community", hindi: "समुदाय", pronunciation: "kəˈmjuːnəti" },
      { word: "during", hindi: "दौरान", pronunciation: "ˈdʊrɪŋ" },
      { word: "crisis", hindi: "संकट", pronunciation: "ˈkraɪsəs" }
    ]
  },
  {
    id: 2,
    title: "The Mango Tree's Gift",
    content: "A small boy planted a mango seed in his grandmother's courtyard. Every day he watered it with love and care. Years passed and the tree grew tall with sweet fruits. The whole neighborhood enjoyed the mangoes that fed many hungry children.",
    wordTranslations: [
      { word: "small", hindi: "छोटा", pronunciation: "smɔːl" },
      { word: "boy", hindi: "लड़का", pronunciation: "bɔɪ" },
      { word: "planted", hindi: "लगाया", pronunciation: "ˈplæntəd" },
      { word: "mango", hindi: "आम", pronunciation: "ˈmæŋɡoʊ" },
      { word: "seed", hindi: "बीज", pronunciation: "siːd" },
      { word: "grandmother's", hindi: "दादी माँ का", pronunciation: "ˈɡrænˌmʌðərz" },
      { word: "courtyard", hindi: "आंगन", pronunciation: "ˈkɔːrtjɑːrd" },
      { word: "every", hindi: "हर", pronunciation: "ˈevri" },
      { word: "watered", hindi: "पानी दिया", pronunciation: "ˈwɔːtərd" },
      { word: "love", hindi: "प्रेम", pronunciation: "lʌv" },
      { word: "care", hindi: "देखभाल", pronunciation: "ker" },
      { word: "years", hindi: "साल", pronunciation: "jɪrz" },
      { word: "passed", hindi: "बीत गए", pronunciation: "pæst" },
      { word: "grew", hindi: "बढ़ा", pronunciation: "ɡruː" },
      { word: "tall", hindi: "लंबा", pronunciation: "tɔːl" },
      { word: "sweet", hindi: "मीठे", pronunciation: "swiːt" },
      { word: "fruits", hindi: "फल", pronunciation: "fruːts" },
      { word: "whole", hindi: "पूरा", pronunciation: "hoʊl" },
      { word: "neighborhood", hindi: "पड़ोस", pronunciation: "ˈneɪbərˌhʊd" },
      { word: "enjoyed", hindi: "आनंद लिया", pronunciation: "ɪnˈdʒɔɪd" },
      { word: "mangoes", hindi: "आम", pronunciation: "ˈmæŋɡoʊz" },
      { word: "fed", hindi: "खिलाया", pronunciation: "fed" },
      { word: "many", hindi: "कई", pronunciation: "ˈmeni" },
      { word: "hungry", hindi: "भूखे", pronunciation: "ˈhʌŋɡri" },
      { word: "children", hindi: "बच्चे", pronunciation: "ˈtʃɪldrən" }
    ]
  },
  {
    id: 3,
    title: "The Brave Peacock",
    content: "Raja the peacock lived in Rajasthan desert near a small oasis. When a cobra threatened the village children, Raja spread his beautiful feathers and danced. The cobra became hypnotized by the dance and forgot about hunting. The children escaped safely while Raja continued his protective dance.",
    wordTranslations: [
      { word: "brave", hindi: "बहादुर", pronunciation: "breɪv" },
      { word: "peacock", hindi: "मोर", pronunciation: "ˈpiːkɑːk" },
      { word: "lived", hindi: "रहता था", pronunciation: "lɪvd" },
      { word: "desert", hindi: "रेगिस्तान", pronunciation: "ˈdezərt" },
      { word: "near", hindi: "पास", pronunciation: "nɪr" },
      { word: "oasis", hindi: "नखलिस्तान", pronunciation: "oʊˈeɪsɪs" },
      { word: "cobra", hindi: "नाग", pronunciation: "ˈkoʊbrə" },
      { word: "threatened", hindi: "धमकी दी", pronunciation: "ˈθretənd" },
      { word: "village", hindi: "गांव", pronunciation: "ˈvɪlɪdʒ" },
      { word: "children", hindi: "बच्चे", pronunciation: "ˈtʃɪldrən" },
      { word: "spread", hindi: "फैलाया", pronunciation: "spred" },
      { word: "beautiful", hindi: "सुंदर", pronunciation: "ˈbjuːtɪfl" },
      { word: "feathers", hindi: "पंख", pronunciation: "ˈfeðərz" },
      { word: "danced", hindi: "नृत्य किया", pronunciation: "dænst" },
      { word: "hypnotized", hindi: "मोहित हो गया", pronunciation: "ˈhɪpnətaɪzd" },
      { word: "dance", hindi: "नृत्य", pronunciation: "dæns" },
      { word: "forgot", hindi: "भूल गया", pronunciation: "fərˈɡɑːt" },
      { word: "hunting", hindi: "शिकार", pronunciation: "ˈhʌntɪŋ" },
      { word: "escaped", hindi: "भाग गए", pronunciation: "ɪˈskeɪpt" },
      { word: "safely", hindi: "सुरक्षित", pronunciation: "ˈseɪfli" },
      { word: "continued", hindi: "जारी रखा", pronunciation: "kənˈtɪnjuːd" },
      { word: "protective", hindi: "सुरक्षात्मक", pronunciation: "prəˈtektɪv" }
    ]
  },
  {
    id: 4,
    title: "The Golden Fish",
    content: "Meera found a golden fish trapped in a small puddle after monsoon rains. The fish promised to grant three wishes if she freed him. Instead of making wishes, Meera carried him to the river. The grateful fish blessed her family with good fortune that lasted generations.",
    wordTranslations: [
      { word: "golden", hindi: "सुनहरी", pronunciation: "ˈɡoʊldən" },
      { word: "fish", hindi: "मछली", pronunciation: "fɪʃ" },
      { word: "found", hindi: "पाया", pronunciation: "faʊnd" },
      { word: "trapped", hindi: "फंसी हुई", pronunciation: "træpt" },
      { word: "puddle", hindi: "गड्ढा", pronunciation: "ˈpʌdl" },
      { word: "after", hindi: "बाद", pronunciation: "ˈæftər" },
      { word: "monsoon", hindi: "मानसून", pronunciation: "mɑːnˈsuːn" },
      { word: "rains", hindi: "बारिश", pronunciation: "reɪnz" },
      { word: "promised", hindi: "वादा किया", pronunciation: "ˈprɑːməst" },
      { word: "grant", hindi: "पूरा करना", pronunciation: "ɡrænt" },
      { word: "three", hindi: "तीन", pronunciation: "θriː" },
      { word: "wishes", hindi: "इच्छाएं", pronunciation: "ˈwɪʃɪz" },
      { word: "freed", hindi: "मुक्त किया", pronunciation: "friːd" },
      { word: "instead", hindi: "बजाय", pronunciation: "ɪnˈsted" },
      { word: "making", hindi: "करना", pronunciation: "ˈmeɪkɪŋ" },
      { word: "carried", hindi: "ले गई", pronunciation: "ˈkærid" },
      { word: "river", hindi: "नदी", pronunciation: "ˈrɪvər" },
      { word: "grateful", hindi: "कृतज्ञ", pronunciation: "ˈɡreɪtfl" },
      { word: "blessed", hindi: "आशीर्वाद दिया", pronunciation: "blest" },
      { word: "family", hindi: "परिवार", pronunciation: "ˈfæməli" },
      { word: "good", hindi: "अच्छा", pronunciation: "ɡʊd" },
      { word: "fortune", hindi: "भाग्य", pronunciation: "ˈfɔːrtʃən" },
      { word: "lasted", hindi: "चला", pronunciation: "ˈlæstəd" },
      { word: "generations", hindi: "पीढ़ियां", pronunciation: "ˌdʒenəˈreɪʃnz" }
    ]
  },
  {
    id: 5,
    title: "The Singing Bulbul",
    content: "In Kashmir valleys lived a bulbul with the sweetest voice. Every morning her songs woke the entire village with joy. When winter came and she fell sick, the villagers took turns caring for her. Their kindness healed her, and spring returned with her beautiful melodies.",
    wordTranslations: [
      { word: "singing", hindi: "गाने वाली", pronunciation: "ˈsɪŋɪŋ" },
      { word: "bulbul", hindi: "बुलबुल", pronunciation: "ˈbʊlbʊl" },
      { word: "valleys", hindi: "घाटी", pronunciation: "ˈvæliz" },
      { word: "sweetest", hindi: "सबसे मीठी", pronunciation: "ˈswiːtəst" },
      { word: "voice", hindi: "आवाज़", pronunciation: "vɔɪs" },
      { word: "every", hindi: "हर", pronunciation: "ˈevri" },
      { word: "morning", hindi: "सुबह", pronunciation: "ˈmɔːrnɪŋ" },
      { word: "songs", hindi: "गाने", pronunciation: "sɔːŋz" },
      { word: "woke", hindi: "जगाया", pronunciation: "woʊk" },
      { word: "entire", hindi: "पूरा", pronunciation: "ɪnˈtaɪər" },
      { word: "village", hindi: "गांव", pronunciation: "ˈvɪlɪdʒ" },
      { word: "joy", hindi: "खुशी", pronunciation: "dʒɔɪ" },
      { word: "winter", hindi: "सर्दी", pronunciation: "ˈwɪntər" },
      { word: "came", hindi: "आई", pronunciation: "keɪm" },
      { word: "fell", hindi: "हो गई", pronunciation: "fel" },
      { word: "sick", hindi: "बीमार", pronunciation: "sɪk" },
      { word: "villagers", hindi: "गांव वाले", pronunciation: "ˈvɪlɪdʒərz" },
      { word: "took", hindi: "लिया", pronunciation: "tʊk" },
      { word: "turns", hindi: "बारी", pronunciation: "tɜːrnz" },
      { word: "caring", hindi: "देखभाल", pronunciation: "ˈkerɪŋ" },
      { word: "kindness", hindi: "दयालुता", pronunciation: "ˈkaɪndnəs" },
      { word: "healed", hindi: "ठीक किया", pronunciation: "hiːld" },
      { word: "spring", hindi: "वसंत", pronunciation: "sprɪŋ" },
      { word: "returned", hindi: "वापस आया", pronunciation: "rɪˈtɜːrnd" },
      { word: "beautiful", hindi: "सुंदर", pronunciation: "ˈbjuːtɪfl" },
      { word: "melodies", hindi: "धुन", pronunciation: "ˈmelədi" }
    ]
  },
  {
    id: 6,
    title: "The Sacred Banyan Tree",
    content: "In the center of Vrindavan stood an ancient banyan tree. Pilgrims from across India came to pray under its shade. One drought year, the tree's roots found underground water and saved the entire town. The grateful villagers declared it sacred and built a small temple nearby.",
    wordTranslations: [
      { word: "sacred", hindi: "पवित्र", pronunciation: "ˈseɪkrəd" },
      { word: "banyan", hindi: "बरगद", pronunciation: "ˈbænjən" },
      { word: "center", hindi: "केंद्र", pronunciation: "ˈsentər" },
      { word: "stood", hindi: "खड़ा था", pronunciation: "stʊd" },
      { word: "ancient", hindi: "प्राचीन", pronunciation: "ˈeɪnʃənt" },
      { word: "pilgrims", hindi: "तीर्थयात्री", pronunciation: "ˈpɪlɡrəmz" },
      { word: "across", hindi: "पार", pronunciation: "əˈkrɔːs" },
      { word: "pray", hindi: "प्रार्थना करना", pronunciation: "preɪ" },
      { word: "shade", hindi: "छाया", pronunciation: "ʃeɪd" },
      { word: "drought", hindi: "सूखा", pronunciation: "draʊt" },
      { word: "roots", hindi: "जड़ें", pronunciation: "ruːts" },
      { word: "underground", hindi: "भूमिगत", pronunciation: "ˈʌndərɡraʊnd" },
      { word: "saved", hindi: "बचाया", pronunciation: "seɪvd" },
      { word: "entire", hindi: "पूरा", pronunciation: "ɪnˈtaɪər" },
      { word: "town", hindi: "शहर", pronunciation: "taʊn" },
      { word: "grateful", hindi: "कृतज्ञ", pronunciation: "ˈɡreɪtfl" },
      { word: "villagers", hindi: "गांव वाले", pronunciation: "ˈvɪlɪdʒərz" },
      { word: "declared", hindi: "घोषित किया", pronunciation: "dɪˈklerd" },
      { word: "built", hindi: "बनाया", pronunciation: "bɪlt" },
      { word: "temple", hindi: "मंदिर", pronunciation: "ˈtempl" },
      { word: "nearby", hindi: "पास में", pronunciation: "ˈnɪrbaɪ" }
    ]
  },
  {
    id: 7,
    title: "The Generous Merchant",
    content: "Ahmed was a spice merchant in Old Delhi market. During festivals, he gave free spices to poor families who couldn't afford them. One Eid, a mysterious old man blessed his shop. From that day, Ahmed's business prospered beyond his wildest dreams.",
    wordTranslations: [
      { word: "generous", hindi: "उदार", pronunciation: "ˈdʒenərəs" },
      { word: "merchant", hindi: "व्यापारी", pronunciation: "ˈmɜːrtʃənt" },
      { word: "spice", hindi: "मसाला", pronunciation: "spaɪs" },
      { word: "market", hindi: "बाज़ार", pronunciation: "ˈmɑːrkət" },
      { word: "during", hindi: "दौरान", pronunciation: "ˈdʊrɪŋ" },
      { word: "festivals", hindi: "त्योहार", pronunciation: "ˈfestəvəlz" },
      { word: "free", hindi: "मुफ्त", pronunciation: "friː" },
      { word: "spices", hindi: "मसाले", pronunciation: "ˈspaɪsəz" },
      { word: "poor", hindi: "गरीब", pronunciation: "pʊr" },
      { word: "families", hindi: "परिवार", pronunciation: "ˈfæməliz" },
      { word: "afford", hindi: "खर्च करना", pronunciation: "əˈfɔːrd" },
      { word: "mysterious", hindi: "रहस्यमय", pronunciation: "mɪˈstɪriəs" },
      { word: "blessed", hindi: "आशीर्वाद दिया", pronunciation: "blest" },
      { word: "shop", hindi: "दुकान", pronunciation: "ʃɑːp" },
      { word: "business", hindi: "व्यापार", pronunciation: "ˈbɪznəs" },
      { word: "prospered", hindi: "फला-फूला", pronunciation: "ˈprɑːspərd" },
      { word: "beyond", hindi: "से अधिक", pronunciation: "bɪˈjɑːnd" },
      { word: "dreams", hindi: "सपने", pronunciation: "driːmz" }
    ]
  },
  {
    id: 8,
    title: "The Dancing Dolphin",
    content: "Off the coast of Goa lived a playful dolphin named Shiva. Every morning, fishermen saw him dancing in the waves. When a tourist boat got lost in fog, Shiva guided them safely to shore. The grateful captain named a beach after this heroic marine friend.",
    wordTranslations: [
      { word: "dancing", hindi: "नृत्य करने वाला", pronunciation: "ˈdænsɪŋ" },
      { word: "dolphin", hindi: "डॉल्फिन", pronunciation: "ˈdɑːlfən" },
      { word: "coast", hindi: "तट", pronunciation: "koʊst" },
      { word: "playful", hindi: "खिलाड़ी", pronunciation: "ˈpleɪfl" },
      { word: "fishermen", hindi: "मछुआरे", pronunciation: "ˈfɪʃərmən" },
      { word: "waves", hindi: "लहरें", pronunciation: "weɪvz" },
      { word: "tourist", hindi: "पर्यटक", pronunciation: "ˈtʊrəst" },
      { word: "boat", hindi: "नाव", pronunciation: "boʊt" },
      { word: "lost", hindi: "खो गई", pronunciation: "lɔːst" },
      { word: "fog", hindi: "कोहरा", pronunciation: "fɔːɡ" },
      { word: "guided", hindi: "मार्गदर्शन किया", pronunciation: "ˈɡaɪdəd" },
      { word: "safely", hindi: "सुरक्षित", pronunciation: "ˈseɪfli" },
      { word: "shore", hindi: "किनारा", pronunciation: "ʃɔːr" },
      { word: "grateful", hindi: "कृतज्ञ", pronunciation: "ˈɡreɪtfl" },
      { word: "captain", hindi: "कप्तान", pronunciation: "ˈkæptən" },
      { word: "beach", hindi: "समुद्री तट", pronunciation: "biːtʃ" },
      { word: "heroic", hindi: "वीर", pronunciation: "həˈroʊɪk" },
      { word: "marine", hindi: "समुद्री", pronunciation: "məˈriːn" },
      { word: "friend", hindi: "मित्र", pronunciation: "frend" }
    ]
  },
  {
    id: 9,
    title: "The Magical Flute Player",
    content: "In Mathura lived a young boy who played the most beautiful flute music. Animals and birds gathered whenever he played his melodies. During a terrible storm, his music calmed the winds and saved the village. People believed his flute had divine powers from Lord Krishna.",
    wordTranslations: [
      { word: "magical", hindi: "जादुई", pronunciation: "ˈmædʒɪkəl" },
      { word: "flute", hindi: "बांसुरी", pronunciation: "fluːt" },
      { word: "player", hindi: "वादक", pronunciation: "ˈpleɪər" },
      { word: "young", hindi: "युवा", pronunciation: "jʌŋ" },
      { word: "played", hindi: "बजाया", pronunciation: "pleɪd" },
      { word: "most", hindi: "सबसे", pronunciation: "moʊst" },
      { word: "beautiful", hindi: "सुंदर", pronunciation: "ˈbjuːtɪfl" },
      { word: "music", hindi: "संगीत", pronunciation: "ˈmjuːzɪk" },
      { word: "animals", hindi: "जानवर", pronunciation: "ˈænəməlz" },
      { word: "birds", hindi: "पक्षी", pronunciation: "bɜːrdz" },
      { word: "gathered", hindi: "इकट्ठे हुए", pronunciation: "ˈɡæðərd" },
      { word: "whenever", hindi: "जब भी", pronunciation: "wenˈevər" },
      { word: "melodies", hindi: "धुन", pronunciation: "ˈmelədi" },
      { word: "terrible", hindi: "भयानक", pronunciation: "ˈterəbl" },
      { word: "storm", hindi: "तूफान", pronunciation: "stɔːrm" },
      { word: "calmed", hindi: "शांत किया", pronunciation: "kɑːmd" },
      { word: "winds", hindi: "हवाएं", pronunciation: "wɪndz" },
      { word: "saved", hindi: "बचाया", pronunciation: "seɪvd" },
      { word: "village", hindi: "गांव", pronunciation: "ˈvɪlɪdʒ" },
      { word: "believed", hindi: "विश्वास करते थे", pronunciation: "bɪˈliːvd" },
      { word: "divine", hindi: "दिव्य", pronunciation: "dɪˈvaɪn" },
      { word: "powers", hindi: "शक्तियां", pronunciation: "ˈpaʊərz" }
    ]
  },
  {
    id: 10,
    title: "The Helpful Monkey",
    content: "Hanuman was a clever monkey who lived near a temple in Hampi. When pilgrims lost their way in the rocky landscape, he guided them to safety. He also protected children from wild animals during their temple visits. The grateful priests considered him a blessed guardian spirit.",
    wordTranslations: [
      { word: "helpful", hindi: "सहायक", pronunciation: "ˈhelpfl" },
      { word: "monkey", hindi: "बंदर", pronunciation: "ˈmʌŋki" },
      { word: "clever", hindi: "चतुर", pronunciation: "ˈklevər" },
      { word: "near", hindi: "पास", pronunciation: "nɪr" },
      { word: "temple", hindi: "मंदिर", pronunciation: "ˈtempl" },
      { word: "pilgrims", hindi: "तीर्थयात्री", pronunciation: "ˈpɪlɡrəmz" },
      { word: "lost", hindi: "खो गए", pronunciation: "lɔːst" },
      { word: "way", hindi: "रास्ता", pronunciation: "weɪ" },
      { word: "rocky", hindi: "चट्टानी", pronunciation: "ˈrɑːki" },
      { word: "landscape", hindi: "भू-दृश्य", pronunciation: "ˈlændskeɪp" },
      { word: "guided", hindi: "मार्गदर्शन किया", pronunciation: "ˈɡaɪdəd" },
      { word: "safety", hindi: "सुरक्षा", pronunciation: "ˈseɪfti" },
      { word: "protected", hindi: "सुरक्षा की", pronunciation: "prəˈtektəd" },
      { word: "children", hindi: "बच्चे", pronunciation: "ˈtʃɪldrən" },
      { word: "wild", hindi: "जंगली", pronunciation: "waɪld" },
      { word: "animals", hindi: "जानवर", pronunciation: "ˈænəməlz" },
      { word: "visits", hindi: "यात्राएं", pronunciation: "ˈvɪzəts" },
      { word: "grateful", hindi: "कृतज्ञ", pronunciation: "ˈɡreɪtfl" },
      { word: "priests", hindi: "पुजारी", pronunciation: "priːsts" },
      { word: "considered", hindi: "माना", pronunciation: "kənˈsɪdərd" },
      { word: "blessed", hindi: "धन्य", pronunciation: "blest" },
      { word: "guardian", hindi: "संरक्षक", pronunciation: "ˈɡɑːrdiən" },
      { word: "spirit", hindi: "आत्मा", pronunciation: "ˈspɪrət" }
    ]
  }
];
