import type { ContentItem } from './contentData';

export const ESSAYS_CONTENT_EXTENDED: ContentItem[] = [
  {
    id: 6,
    title: "Indian Spices and Their Benefits",
    content: "Indian cuisine uses various spices that are healthy and flavorful. Turmeric fights infections and reduces inflammation. Cumin aids digestion while cardamom freshens breath. These natural ingredients make Indian food both tasty and nutritious.",
    wordTranslations: [
      { word: "cuisine", hindi: "व्यंजन", pronunciation: "kwɪˈziːn" },
      { word: "spices", hindi: "मसाले", pronunciation: "ˈspaɪsɪz" },
      { word: "healthy", hindi: "स्वस्थ", pronunciation: "ˈhelθi" },
      { word: "flavorful", hindi: "स्वादिष्ट", pronunciation: "ˈfleɪvərfl" },
      { word: "turmeric", hindi: "हल्दी", pronunciation: "ˈtɜːrmərɪk" },
      { word: "fights", hindi: "लड़ता है", pronunciation: "faɪts" },
      { word: "infections", hindi: "संक्रमण", pronunciation: "ɪnˈfekʃnz" },
      { word: "reduces", hindi: "कम करता है", pronunciation: "rɪˈduːsɪz" },
      { word: "inflammation", hindi: "सूजन", pronunciation: "ˌɪnfləˈmeɪʃn" },
      { word: "cumin", hindi: "जीरा", pronunciation: "ˈkuːmɪn" },
      { word: "aids", hindi: "सहायता करता है", pronunciation: "eɪdz" },
      { word: "digestion", hindi: "पाचन", pronunciation: "daɪˈdʒestʃən" },
      { word: "cardamom", hindi: "इलायची", pronunciation: "ˈkɑːrdəməm" },
      { word: "freshens", hindi: "ताज़ा करता है", pronunciation: "ˈfreʃənz" },
      { word: "breath", hindi: "सांस", pronunciation: "breθ" },
      { word: "natural", hindi: "प्राकृतिक", pronunciation: "ˈnætʃərəl" },
      { word: "ingredients", hindi: "सामग्री", pronunciation: "ɪnˈɡriːdiənts" },
      { word: "nutritious", hindi: "पौष्टिक", pronunciation: "nuˈtrɪʃəs" }
    ]
  },
  {
    id: 7,
    title: "The Beauty of Himalayas",
    content: "The Himalayan mountains are India's crown jewel. Snow-capped peaks touch the sky while rivers flow down the valleys. Many pilgrims visit sacred temples hidden in these mountains. The fresh air and peaceful environment provide perfect escape from city life.",
    wordTranslations: [
      { word: "mountains", hindi: "पहाड़", pronunciation: "ˈmaʊntənz" },
      { word: "crown", hindi: "मुकुट", pronunciation: "kraʊn" },
      { word: "jewel", hindi: "रत्न", pronunciation: "ˈdʒuːəl" },
      { word: "snow-capped", hindi: "बर्फ से ढके", pronunciation: "snoʊ kæpt" },
      { word: "peaks", hindi: "चोटियां", pronunciation: "piːks" },
      { word: "touch", hindi: "छूना", pronunciation: "tʌtʃ" },
      { word: "sky", hindi: "आसमान", pronunciation: "skaɪ" },
      { word: "rivers", hindi: "नदियां", pronunciation: "ˈrɪvərz" },
      { word: "flow", hindi: "बहना", pronunciation: "floʊ" },
      { word: "valleys", hindi: "घाटी", pronunciation: "ˈvæliz" },
      { word: "pilgrims", hindi: "तीर्थयात्री", pronunciation: "ˈpɪlɡrəmz" },
      { word: "sacred", hindi: "पवित्र", pronunciation: "ˈseɪkrəd" },
      { word: "temples", hindi: "मंदिर", pronunciation: "ˈtemplz" },
      { word: "hidden", hindi: "छिपे हुए", pronunciation: "ˈhɪdn" },
      { word: "fresh", hindi: "ताज़ी", pronunciation: "freʃ" },
      { word: "peaceful", hindi: "शांतिपूर्ण", pronunciation: "ˈpiːsfl" },
      { word: "environment", hindi: "वातावरण", pronunciation: "ɪnˈvaɪrənmənt" },
      { word: "escape", hindi: "भागना", pronunciation: "ɪˈskeɪp" }
    ]
  },
  {
    id: 8,
    title: "Indian Railways Journey",
    content: "Traveling by train in India is an unforgettable experience. From luxury coaches to general compartments, trains carry millions daily. Vendors sell tea, snacks, and meals at every station. The journey offers beautiful landscapes and chance to meet diverse people.",
    wordTranslations: [
      { word: "traveling", hindi: "यात्रा करना", pronunciation: "ˈtrævəlɪŋ" },
      { word: "train", hindi: "ट्रेन", pronunciation: "treɪn" },
      { word: "unforgettable", hindi: "अविस्मरणीय", pronunciation: "ˌʌnfərˈɡetəbl" },
      { word: "experience", hindi: "अनुभव", pronunciation: "ɪkˈspɪriəns" },
      { word: "luxury", hindi: "लक्जरी", pronunciation: "ˈlʌkʃəri" },
      { word: "coaches", hindi: "डिब्बे", pronunciation: "ˈkoʊtʃɪz" },
      { word: "general", hindi: "सामान्य", pronunciation: "ˈdʒenərəl" },
      { word: "compartments", hindi: "डिब्बे", pronunciation: "kəmˈpɑːrtmənts" },
      { word: "carry", hindi: "ले जाना", pronunciation: "ˈkæri" },
      { word: "millions", hindi: "लाखों", pronunciation: "ˈmɪljənz" },
      { word: "daily", hindi: "रोज़ाना", pronunciation: "ˈdeɪli" },
      { word: "vendors", hindi: "विक्रेता", pronunciation: "ˈvendərz" },
      { word: "snacks", hindi: "नाश्ता", pronunciation: "snæks" },
      { word: "meals", hindi: "भोजन", pronunciation: "miːlz" },
      { word: "station", hindi: "स्टेशन", pronunciation: "ˈsteɪʃn" },
      { word: "journey", hindi: "यात्रा", pronunciation: "ˈdʒɜːrni" },
      { word: "offers", hindi: "प्रदान करता है", pronunciation: "ˈɔːfərz" },
      { word: "landscapes", hindi: "दृश्य", pronunciation: "ˈlændskeɪps" },
      { word: "chance", hindi: "अवसर", pronunciation: "tʃæns" },
      { word: "diverse", hindi: "विविध", pronunciation: "daɪˈvɜːrs" }
    ]
  },
  {
    id: 9,
    title: "Village Life in India",
    content: "Indian villages preserve traditional culture and simple living. Farmers wake up early to tend their fields with buffaloes and tractors. Children attend schools while grandparents share ancient stories. Community festivals unite everyone in celebration and joy.",
    wordTranslations: [
      { word: "villages", hindi: "गांव", pronunciation: "ˈvɪlɪdʒɪz" },
      { word: "preserve", hindi: "संरक्षित करना", pronunciation: "prɪˈzɜːrv" },
      { word: "traditional", hindi: "पारंपरिक", pronunciation: "trəˈdɪʃənəl" },
      { word: "culture", hindi: "संस्कृति", pronunciation: "ˈkʌltʃər" },
      { word: "simple", hindi: "सरल", pronunciation: "ˈsɪmpl" },
      { word: "living", hindi: "जीवन", pronunciation: "ˈlɪvɪŋ" },
      { word: "farmers", hindi: "किसान", pronunciation: "ˈfɑːrmərz" },
      { word: "early", hindi: "जल्दी", pronunciation: "ˈɜːrli" },
      { word: "tend", hindi: "देखभाल करना", pronunciation: "tend" },
      { word: "fields", hindi: "खेत", pronunciation: "fiːldz" },
      { word: "buffaloes", hindi: "भैंस", pronunciation: "ˈbʌfəloʊz" },
      { word: "tractors", hindi: "ट्रैक्टर", pronunciation: "ˈtræktərz" },
      { word: "children", hindi: "बच्चे", pronunciation: "ˈtʃɪldrən" },
      { word: "attend", hindi: "जाना", pronunciation: "əˈtend" },
      { word: "schools", hindi: "स्कूल", pronunciation: "skuːlz" },
      { word: "grandparents", hindi: "दादा-दादी", pronunciation: "ˈɡrænˌperənts" },
      { word: "share", hindi: "साझा करना", pronunciation: "ʃer" },
      { word: "ancient", hindi: "प्राचीन", pronunciation: "ˈeɪnʃənt" },
      { word: "stories", hindi: "कहानियां", pronunciation: "ˈstɔːriz" },
      { word: "community", hindi: "समुदाय", pronunciation: "kəˈmjuːnəti" },
      { word: "festivals", hindi: "त्योहार", pronunciation: "ˈfestɪvəlz" },
      { word: "unite", hindi: "एकजुट करना", pronunciation: "juˈnaɪt" },
      { word: "celebration", hindi: "उत्सव", pronunciation: "ˌseləˈbreɪʃn" }
    ]
  },
  {
    id: 10,
    title: "The Sacred Ganges River",
    content: "The Ganges is considered the holiest river in India. Millions of devotees take holy baths believing it cleanses their sins. The river flows through many important cities providing water for agriculture. Despite pollution challenges, efforts continue to clean this sacred waterway.",
    wordTranslations: [
      { word: "sacred", hindi: "पवित्र", pronunciation: "ˈseɪkrəd" },
      { word: "considered", hindi: "माना जाता है", pronunciation: "kənˈsɪdərd" },
      { word: "holiest", hindi: "सबसे पवित्र", pronunciation: "ˈhoʊliəst" },
      { word: "river", hindi: "नदी", pronunciation: "ˈrɪvər" },
      { word: "millions", hindi: "लाखों", pronunciation: "ˈmɪljənz" },
      { word: "devotees", hindi: "भक्त", pronunciation: "ˌdevəˈtiːz" },
      { word: "holy", hindi: "पवित्र", pronunciation: "ˈhoʊli" },
      { word: "baths", hindi: "स्नान", pronunciation: "bæθs" },
      { word: "believing", hindi: "विश्वास करना", pronunciation: "bɪˈliːvɪŋ" },
      { word: "cleanses", hindi: "साफ करता है", pronunciation: "ˈklenzɪz" },
      { word: "sins", hindi: "पाप", pronunciation: "sɪnz" },
      { word: "flows", hindi: "बहती है", pronunciation: "floʊz" },
      { word: "through", hindi: "से होकर", pronunciation: "θruː" },
      { word: "important", hindi: "महत्वपूर्ण", pronunciation: "ɪmˈpɔːrtənt" },
      { word: "cities", hindi: "शहर", pronunciation: "ˈsɪtiz" },
      { word: "providing", hindi: "प्रदान करना", pronunciation: "prəˈvaɪdɪŋ" },
      { word: "water", hindi: "पानी", pronunciation: "ˈwɔːtər" },
      { word: "agriculture", hindi: "कृषि", pronunciation: "ˈæɡrɪkʌltʃər" },
      { word: "despite", hindi: "के बावजूद", pronunciation: "dɪˈspaɪt" },
      { word: "pollution", hindi: "प्रदूषण", pronunciation: "pəˈluːʃn" },
      { word: "challenges", hindi: "चुनौतियां", pronunciation: "ˈtʃælɪndʒəz" },
      { word: "efforts", hindi: "प्रयास", pronunciation: "ˈefərts" },
      { word: "continue", hindi: "जारी रखना", pronunciation: "kənˈtɪnju" },
      { word: "clean", hindi: "साफ करना", pronunciation: "kliːn" },
      { word: "waterway", hindi: "जलमार्ग", pronunciation: "ˈwɔːtərweɪ" }
    ]
  }
  // ... This would continue for 95 more essays
];
