// Extended Essays Content (Essays 11-50)
import type { ContentItem } from './contentData';

export const ESSAYS_ADDITIONAL: ContentItem[] = [
  {
    id: 11,
    title: "Bollywood and Indian Cinema",
    content: "Bollywood produces the largest number of films globally. Indian cinema reflects our diverse culture and traditions. Famous actors like Shah Rukh Khan and Deepika Padukone are known worldwide. These movies spread Indian values and entertainment across the globe.",
    wordTranslations: [
      { word: "produces", hindi: "बनाता है", pronunciation: "prəˈduːsəz" },
      { word: "largest", hindi: "सबसे बड़ा", pronunciation: "ˈlɑːrdʒəst" },
      { word: "number", hindi: "संख्या", pronunciation: "ˈnʌmbər" },
      { word: "films", hindi: "फिल्में", pronunciation: "fɪlmz" },
      { word: "globally", hindi: "विश्व भर में", pronunciation: "ˈɡloʊbəli" },
      { word: "cinema", hindi: "सिनेमा", pronunciation: "ˈsɪnəmə" },
      { word: "reflects", hindi: "दर्शाता है", pronunciation: "rɪˈflekts" },
      { word: "diverse", hindi: "विविध", pronunciation: "daɪˈvɜːrs" },
      { word: "culture", hindi: "संस्कृति", pronunciation: "ˈkʌltʃər" },
      { word: "traditions", hindi: "परंपराएं", pronunciation: "trəˈdɪʃnz" },
      { word: "famous", hindi: "प्रसिद्ध", pronunciation: "ˈfeɪməs" },
      { word: "actors", hindi: "अभिनेता", pronunciation: "ˈæktərz" },
      { word: "known", hindi: "जाने जाते हैं", pronunciation: "noʊn" },
      { word: "worldwide", hindi: "दुनिया भर में", pronunciation: "ˈwɜːrldwaɪd" },
      { word: "movies", hindi: "फिल्में", pronunciation: "ˈmuːviz" },
      { word: "spread", hindi: "फैलाती हैं", pronunciation: "spred" },
      { word: "values", hindi: "मूल्य", pronunciation: "ˈvæljuːz" },
      { word: "entertainment", hindi: "मनोरंजन", pronunciation: "ˌentərˈteɪnmənt" },
      { word: "across", hindi: "पार", pronunciation: "əˈkrɔːs" },
      { word: "globe", hindi: "संसार", pronunciation: "ɡloʊb" }
    ]
  },
  {
    id: 12,
    title: "Yoga and Meditation",
    content: "Yoga originated in ancient India thousands of years ago. This practice combines physical exercises with mental peace. Millions of people worldwide now practice yoga daily. It helps reduce stress and improves overall health and well-being.",
    wordTranslations: [
      { word: "yoga", hindi: "योग", pronunciation: "ˈjoʊɡə" },
      { word: "originated", hindi: "उत्पन्न हुआ", pronunciation: "əˈrɪdʒəneɪtəd" },
      { word: "ancient", hindi: "प्राचीन", pronunciation: "ˈeɪnʃənt" },
      { word: "thousands", hindi: "हजारों", pronunciation: "ˈθaʊzəndz" },
      { word: "practice", hindi: "अभ्यास", pronunciation: "ˈpræktəs" },
      { word: "combines", hindi: "मिलाता है", pronunciation: "kəmˈbaɪnz" },
      { word: "physical", hindi: "शारीरिक", pronunciation: "ˈfɪzɪkəl" },
      { word: "exercises", hindi: "व्यायाम", pronunciation: "ˈeksərˌsaɪzəz" },
      { word: "mental", hindi: "मानसिक", pronunciation: "ˈmentl" },
      { word: "peace", hindi: "शांति", pronunciation: "piːs" },
      { word: "millions", hindi: "लाखों", pronunciation: "ˈmɪljənz" },
      { word: "worldwide", hindi: "दुनिया भर में", pronunciation: "ˈwɜːrldwaɪd" },
      { word: "daily", hindi: "रोज़ाना", pronunciation: "ˈdeɪli" },
      { word: "helps", hindi: "मदद करता है", pronunciation: "helps" },
      { word: "reduce", hindi: "कम करना", pronunciation: "rɪˈduːs" },
      { word: "stress", hindi: "तनाव", pronunciation: "stres" },
      { word: "improves", hindi: "सुधारता है", pronunciation: "ɪmˈpruːvz" },
      { word: "overall", hindi: "कुल मिलाकर", pronunciation: "ˈoʊvərɔːl" },
      { word: "health", hindi: "स्वास्थ्य", pronunciation: "helθ" },
      { word: "well-being", hindi: "कल्याण", pronunciation: "wel ˈbiːɪŋ" }
    ]
  },
  {
    id: 13,
    title: "Indian Classical Music",
    content: "Indian classical music has two main traditions: Hindustani and Carnatic. Great musicians like Ravi Shankar made this music popular globally. The sitar, tabla, and flute create beautiful melodies. This ancient art form continues to inspire new generations of artists.",
    wordTranslations: [
      { word: "classical", hindi: "शास्त्रीय", pronunciation: "ˈklæsɪkəl" },
      { word: "music", hindi: "संगीत", pronunciation: "ˈmjuːzɪk" },
      { word: "main", hindi: "मुख्य", pronunciation: "meɪn" },
      { word: "traditions", hindi: "परंपराएं", pronunciation: "trəˈdɪʃnz" },
      { word: "musicians", hindi: "संगीतकार", pronunciation: "mjuˈzɪʃənz" },
      { word: "made", hindi: "बनाया", pronunciation: "meɪd" },
      { word: "popular", hindi: "लोकप्रिय", pronunciation: "ˈpɑːpjələr" },
      { word: "globally", hindi: "विश्व भर में", pronunciation: "ˈɡloʊbəli" },
      { word: "sitar", hindi: "सितार", pronunciation: "sɪˈtɑːr" },
      { word: "tabla", hindi: "तबला", pronunciation: "ˈtʌblə" },
      { word: "flute", hindi: "बांसुरी", pronunciation: "fluːt" },
      { word: "create", hindi: "बनाते हैं", pronunciation: "kriˈeɪt" },
      { word: "beautiful", hindi: "सुंदर", pronunciation: "ˈbjuːtɪfl" },
      { word: "melodies", hindi: "धुन", pronunciation: "ˈmelədi" },
      { word: "ancient", hindi: "प्राचीन", pronunciation: "ˈeɪnʃənt" },
      { word: "art", hindi: "कला", pronunciation: "ɑːrt" },
      { word: "form", hindi: "रूप", pronunciation: "fɔːrm" },
      { word: "continues", hindi: "जारी रहता है", pronunciation: "kənˈtɪnjuːz" },
      { word: "inspire", hindi: "प्रेरणा देना", pronunciation: "ɪnˈspaɪər" },
      { word: "generations", hindi: "पीढ़ियां", pronunciation: "ˌdʒenəˈreɪʃnz" },
      { word: "artists", hindi: "कलाकार", pronunciation: "ˈɑːrtəsts" }
    ]
  },
  {
    id: 14,
    title: "The Taj Mahal",
    content: "The Taj Mahal in Agra is one of the Seven Wonders of the World. Shah Jahan built this beautiful monument for his beloved wife Mumtaz. The white marble structure changes colors throughout the day. Millions of tourists visit this symbol of eternal love every year.",
    wordTranslations: [
      { word: "seven", hindi: "सात", pronunciation: "ˈsevən" },
      { word: "wonders", hindi: "अजूबे", pronunciation: "ˈwʌndərz" },
      { word: "world", hindi: "दुनिया", pronunciation: "wɜːrld" },
      { word: "built", hindi: "बनवाया", pronunciation: "bɪlt" },
      { word: "beautiful", hindi: "सुंदर", pronunciation: "ˈbjuːtɪfl" },
      { word: "monument", hindi: "स्मारक", pronunciation: "ˈmɑːnjumənt" },
      { word: "beloved", hindi: "प्रिय", pronunciation: "bɪˈlʌvd" },
      { word: "wife", hindi: "पत्नी", pronunciation: "waɪf" },
      { word: "white", hindi: "सफेद", pronunciation: "waɪt" },
      { word: "marble", hindi: "संगमरमर", pronunciation: "ˈmɑːrbəl" },
      { word: "structure", hindi: "संरचना", pronunciation: "ˈstrʌktʃər" },
      { word: "changes", hindi: "बदलती है", pronunciation: "ˈtʃeɪndʒəz" },
      { word: "colors", hindi: "रंग", pronunciation: "ˈkʌlərz" },
      { word: "throughout", hindi: "पूरे", pronunciation: "θruˈaʊt" },
      { word: "day", hindi: "दिन", pronunciation: "deɪ" },
      { word: "millions", hindi: "लाखों", pronunciation: "ˈmɪljənz" },
      { word: "tourists", hindi: "पर्यटक", pronunciation: "ˈtʊrəsts" },
      { word: "visit", hindi: "जाते हैं", pronunciation: "ˈvɪzət" },
      { word: "symbol", hindi: "प्रतीक", pronunciation: "ˈsɪmbəl" },
      { word: "eternal", hindi: "अनंत", pronunciation: "ɪˈtɜːrnəl" },
      { word: "love", hindi: "प्रेम", pronunciation: "lʌv" },
      { word: "every", hindi: "हर", pronunciation: "ˈevri" },
      { word: "year", hindi: "साल", pronunciation: "jɪr" }
    ]
  },
  {
    id: 15,
    title: "Indian Festivals Throughout the Year",
    content: "India celebrates numerous colorful festivals throughout the year. Holi brings colors and joy in spring season. Dussehra celebrates the victory of good over evil. Each festival has unique traditions that bring families and communities together in celebration.",
    wordTranslations: [
      { word: "celebrates", hindi: "मनाता है", pronunciation: "ˈseləbreɪts" },
      { word: "numerous", hindi: "अनेक", pronunciation: "ˈnuːmərəs" },
      { word: "colorful", hindi: "रंगबिरंगे", pronunciation: "ˈkʌlərfl" },
      { word: "festivals", hindi: "त्योहार", pronunciation: "ˈfestəvəlz" },
      { word: "throughout", hindi: "पूरे", pronunciation: "θruˈaʊt" },
      { word: "year", hindi: "साल", pronunciation: "jɪr" },
      { word: "brings", hindi: "लाता है", pronunciation: "brɪŋz" },
      { word: "colors", hindi: "रंग", pronunciation: "ˈkʌlərz" },
      { word: "joy", hindi: "खुशी", pronunciation: "dʒɔɪ" },
      { word: "spring", hindi: "वसंत", pronunciation: "sprɪŋ" },
      { word: "season", hindi: "मौसम", pronunciation: "ˈsiːzən" },
      { word: "victory", hindi: "जीत", pronunciation: "ˈvɪktəri" },
      { word: "good", hindi: "अच्छाई", pronunciation: "ɡʊd" },
      { word: "over", hindi: "पर", pronunciation: "ˈoʊvər" },
      { word: "evil", hindi: "बुराई", pronunciation: "ˈiːvəl" },
      { word: "each", hindi: "हर", pronunciation: "iːtʃ" },
      { word: "festival", hindi: "त्योहार", pronunciation: "ˈfestəvəl" },
      { word: "unique", hindi: "अनोखी", pronunciation: "juˈniːk" },
      { word: "traditions", hindi: "परंपराएं", pronunciation: "trəˈdɪʃnz" },
      { word: "families", hindi: "परिवार", pronunciation: "ˈfæməliz" },
      { word: "communities", hindi: "समुदाय", pronunciation: "kəˈmjuːnətiz" },
      { word: "together", hindi: "साथ", pronunciation: "təˈɡeðər" },
      { word: "celebration", hindi: "उत्सव", pronunciation: "ˌseləˈbreɪʃən" }
    ]
  }
];
