// Extended Stories Content (Stories 6-30)
import type { ContentItem } from './contentData';

export const STORIES_ADDITIONAL: ContentItem[] = [
  {
    id: 6,
    title: "The Sacred Banyan Tree",
    content: "In the center of Vrindavan stood an ancient banyan tree. Pilgrims from across India came to pray under its shade. One drought year, the tree's roots found underground water and saved the entire town. The grateful villagers declared it sacred and built a small temple nearby.",
    wordTranslations: [
      { word: "sacred", hindi: "पवित्र", pronunciation: "ˈseɪkrəd" },
      { word: "banyan", hindi: "बरगद", pronunciation: "ˈbænjən" },
      { word: "tree", hindi: "पेड़", pronunciation: "triː" },
      { word: "center", hindi: "केंद्र", pronunciation: "ˈsentər" },
      { word: "stood", hindi: "खड़ा था", pronunciation: "stʊd" },
      { word: "ancient", hindi: "प्राचीन", pronunciation: "ˈeɪnʃənt" },
      { word: "pilgrims", hindi: "तीर्थयात्री", pronunciation: "ˈpɪlɡrəmz" },
      { word: "across", hindi: "पार", pronunciation: "əˈkrɔːs" },
      { word: "came", hindi: "आए", pronunciation: "keɪm" },
      { word: "pray", hindi: "प्रार्थना करना", pronunciation: "preɪ" },
      { word: "under", hindi: "नीचे", pronunciation: "ˈʌndər" },
      { word: "shade", hindi: "छाया", pronunciation: "ʃeɪd" },
      { word: "drought", hindi: "सूखा", pronunciation: "draʊt" },
      { word: "year", hindi: "साल", pronunciation: "jɪr" },
      { word: "roots", hindi: "जड़ें", pronunciation: "ruːts" },
      { word: "found", hindi: "पाया", pronunciation: "faʊnd" },
      { word: "underground", hindi: "भूमिगत", pronunciation: "ˈʌndərɡraʊnd" },
      { word: "water", hindi: "पानी", pronunciation: "ˈwɔːtər" },
      { word: "saved", hindi: "बचाया", pronunciation: "seɪvd" },
      { word: "entire", hindi: "पूरा", pronunciation: "ɪnˈtaɪər" },
      { word: "town", hindi: "शहर", pronunciation: "taʊn" },
      { word: "grateful", hindi: "कृतज्ञ", pronunciation: "ˈɡreɪtfl" },
      { word: "villagers", hindi: "गांव वाले", pronunciation: "ˈvɪlɪdʒərz" },
      { word: "declared", hindi: "घोषित किया", pronunciation: "dɪˈklerd" },
      { word: "built", hindi: "बनाया", pronunciation: "bɪlt" },
      { word: "small", hindi: "छोटा", pronunciation: "smɔːl" },
      { word: "temple", hindi: "मंदिर", pronunciation: "ˈtempl" },
      { word: "nearby", hindi: "पास में", pronunciation: "ˈnɪrbaɪ" }
    ]
  },
  {
    id: 7,
    title: "The Generous Merchant",
    content: "Ahmed was a spice merchant in Old Delhi market. During festivals, he gave free spices to poor families who couldn't afford them. One Eid, a mysterious old man blessed his shop. From that day, Ahmed's business prospered beyond his wildest dreams.",
    wordTranslations: [
      { word: "generous", hindi: "उदार", pronunciation: "ˈdʒenərəs" },
      { word: "merchant", hindi: "व्यापारी", pronunciation: "ˈmɜːrtʃənt" },
      { word: "spice", hindi: "मसाला", pronunciation: "spaɪs" },
      { word: "market", hindi: "बाज़ार", pronunciation: "ˈmɑːrkət" },
      { word: "during", hindi: "दौरान", pronunciation: "ˈdʊrɪŋ" },
      { word: "festivals", hindi: "त्योहार", pronunciation: "ˈfestəvəlz" },
      { word: "gave", hindi: "दिया", pronunciation: "ɡeɪv" },
      { word: "free", hindi: "मुफ्त", pronunciation: "friː" },
      { word: "spices", hindi: "मसाले", pronunciation: "ˈspaɪsəz" },
      { word: "poor", hindi: "गरीब", pronunciation: "pʊr" },
      { word: "families", hindi: "परिवार", pronunciation: "ˈfæməliz" },
      { word: "couldn't", hindi: "नहीं कर सकते थे", pronunciation: "ˈkʊdnt" },
      { word: "afford", hindi: "खर्च करना", pronunciation: "əˈfɔːrd" },
      { word: "mysterious", hindi: "रहस्यमय", pronunciation: "mɪˈstɪriəs" },
      { word: "old", hindi: "बूढ़ा", pronunciation: "oʊld" },
      { word: "man", hindi: "आदमी", pronunciation: "mæn" },
      { word: "blessed", hindi: "आशीर्वाद दिया", pronunciation: "blest" },
      { word: "shop", hindi: "दुकान", pronunciation: "ʃɑːp" },
      { word: "from", hindi: "से", pronunciation: "frəm" },
      { word: "that", hindi: "उस", pronunciation: "ðæt" },
      { word: "day", hindi: "दिन", pronunciation: "deɪ" },
      { word: "business", hindi: "व्यापार", pronunciation: "ˈbɪznəs" },
      { word: "prospered", hindi: "फला-फूला", pronunciation: "ˈprɑːspərd" },
      { word: "beyond", hindi: "से अधिक", pronunciation: "bɪˈjɑːnd" },
      { word: "wildest", hindi: "सबसे बड़े", pronunciation: "ˈwaɪldəst" },
      { word: "dreams", hindi: "सपने", pronunciation: "driːmz" }
    ]
  },
  {
    id: 8,
    title: "The Dancing Dolphin",
    content: "Off the coast of Goa lived a playful dolphin named Shiva. Every morning, fishermen saw him dancing in the waves. When a tourist boat got lost in fog, Shiva guided them safely to shore. The grateful captain named a beach after this heroic marine friend.",
    wordTranslations: [
      { word: "dancing", hindi: "नृत्य करने वाला", pronunciation: "ˈdænsɪŋ" },
      { word: "dolphin", hindi: "डॉल्फिन", pronunciation: "ˈdɑːlfən" },
      { word: "coast", hindi: "तट", pronunciation: "koʊst" },
      { word: "lived", hindi: "रहता था", pronunciation: "lɪvd" },
      { word: "playful", hindi: "खिलाड़ी", pronunciation: "ˈpleɪfl" },
      { word: "named", hindi: "नाम", pronunciation: "neɪmd" },
      { word: "every", hindi: "हर", pronunciation: "ˈevri" },
      { word: "morning", hindi: "सुबह", pronunciation: "ˈmɔːrnɪŋ" },
      { word: "fishermen", hindi: "मछुआरे", pronunciation: "ˈfɪʃərmən" },
      { word: "saw", hindi: "देखा", pronunciation: "sɔː" },
      { word: "dancing", hindi: "नृत्य करते हुए", pronunciation: "ˈdænsɪŋ" },
      { word: "waves", hindi: "लहरें", pronunciation: "weɪvz" },
      { word: "when", hindi: "जब", pronunciation: "wen" },
      { word: "tourist", hindi: "पर्यटक", pronunciation: "ˈtʊrəst" },
      { word: "boat", hindi: "नाव", pronunciation: "boʊt" },
      { word: "got", hindi: "हो गई", pronunciation: "ɡɑːt" },
      { word: "lost", hindi: "खो गई", pronunciation: "lɔːst" },
      { word: "fog", hindi: "कोहरा", pronunciation: "fɔːɡ" },
      { word: "guided", hindi: "मार्गदर्शन किया", pronunciation: "ˈɡaɪdəd" },
      { word: "them", hindi: "उन्हें", pronunciation: "ðem" },
      { word: "safely", hindi: "सुरक्षित", pronunciation: "ˈseɪfli" },
      { word: "shore", hindi: "किनारा", pronunciation: "ʃɔːr" },
      { word: "grateful", hindi: "कृतज्ञ", pronunciation: "ˈɡreɪtfl" },
      { word: "captain", hindi: "कप्तान", pronunciation: "ˈkæptən" },
      { word: "beach", hindi: "समुद्री तट", pronunciation: "biːtʃ" },
      { word: "after", hindi: "के नाम पर", pronunciation: "ˈæftər" },
      { word: "heroic", hindi: "वीर", pronunciation: "həˈroʊɪk" },
      { word: "marine", hindi: "समुद्री", pronunciation: "məˈriːn" },
      { word: "friend", hindi: "मित्र", pronunciation: "frend" }
    ]
  }
];
